Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, host: 4500, guest: 8080  # Jenkins
  config.vm.provision :shell, path: "bootstrap-buildserver.sh"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
  	v.cpus = 1
  end
end