# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, host: 4500, guest: 80    # Apache
  config.vm.network :forwarded_port, host: 1022, guest: 1022  # ssh into the Docker container
  config.vm.provision :shell, path: "bootstrap-openpkw-kalkulator-obwodowy-web-docker.sh"
  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
  	v.cpus = 1
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
end