# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, host: 4500, guest: 80
  config.vm.network :forwarded_port, host: 4501, guest: 8080
  config.vm.provision :shell, path: "bootstrap-jenkins-docker.sh"
 
  config.vm.provider "virtualbox" do |v|
  	v.memory = 4096
  	v.cpus = 1
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
end