#!/bin/bash
### BEGIN INIT INFO
# Provides:          wildfly9
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop WildFly 9
### END INIT INFO
# chkconfig: 35 92 1

## Include some script files in order to set and export environmental variables
## as well as add the appropriate executables to $PATH.
[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
[ -r /etc/profile.d/wildfly.sh ] && . /etc/profile.d/wildfly.sh

WILDFLY_HOME=/usr/share/wildfly

OPTS="$OPTS -Dorg.apache.tomcat.util.http.ServerCookie.ALLOW_HTTP_SEPARATORS_IN_V0=true"
OPTS="$OPTS -Djboss.bind.address.management=0.0.0.0"
OPTS="$OPTS -Djboss.bind.address=0.0.0.0"

case "$1" in
    start)

        start-stop-daemon --start --quiet --background --chuid wildfly --exec ${WILDFLY_HOME}/bin/standalone.sh -- $OPTS
    ;;
    stop)
        echo "Stopping WildFly 9..."
        start-stop-daemon --start --quiet --background --chuid wildfly --exec ${WILDFLY_HOME}/bin/jboss-cli.sh -- --connect command=:shutdown
    ;;
    *)
        echo "Usage: /etc/init.d/wildfly9 {start|stop}"; exit 1;
    ;;
esac

exit 0

